Traceback (most recent call last):
  File "C:\Users\almand\Anaconda3\envs\JupyterBook_env\lib\site-packages\jupyter_cache\executors\utils.py", line 51, in single_nb_execution
    executenb(
  File "C:\Users\almand\Anaconda3\envs\JupyterBook_env\lib\site-packages\nbclient\client.py", line 1093, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\almand\Anaconda3\envs\JupyterBook_env\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Users\almand\Anaconda3\envs\JupyterBook_env\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "C:\Users\almand\Anaconda3\envs\JupyterBook_env\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:\Users\almand\Anaconda3\envs\JupyterBook_env\lib\site-packages\nbclient\client.py", line 559, in async_execute
    await self.async_execute_cell(
  File "C:\Users\almand\Anaconda3\envs\JupyterBook_env\lib\site-packages\nbclient\client.py", line 854, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "C:\Users\almand\Anaconda3\envs\JupyterBook_env\lib\site-packages\nbclient\client.py", line 756, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
file = pd.read_csv(aerograv_data, skiprows=skiprow, sep= ' +', engine='python' )
file.head()
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mFileNotFoundError[0m                         Traceback (most recent call last)
[1;32m<ipython-input-5-05b73d4bce79>[0m in [0;36m<module>[1;34m[0m
[1;32m----> 1[1;33m [0mfile[0m [1;33m=[0m [0mpd[0m[1;33m.[0m[0mread_csv[0m[1;33m([0m[0maerograv_data[0m[1;33m,[0m [0mskiprows[0m[1;33m=[0m[0mskiprow[0m[1;33m,[0m [0msep[0m[1;33m=[0m [1;34m' +'[0m[1;33m,[0m [0mengine[0m[1;33m=[0m[1;34m'python'[0m [1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m      2[0m [0mfile[0m[1;33m.[0m[0mhead[0m[1;33m([0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m

[1;32m~\Anaconda3\envs\JupyterBook_env\lib\site-packages\pandas\io\parsers.py[0m in [0;36mread_csv[1;34m(filepath_or_buffer, sep, delimiter, header, names, index_col, usecols, squeeze, prefix, mangle_dupe_cols, dtype, engine, converters, true_values, false_values, skipinitialspace, skiprows, skipfooter, nrows, na_values, keep_default_na, na_filter, verbose, skip_blank_lines, parse_dates, infer_datetime_format, keep_date_col, date_parser, dayfirst, cache_dates, iterator, chunksize, compression, thousands, decimal, lineterminator, quotechar, quoting, doublequote, escapechar, comment, encoding, dialect, error_bad_lines, warn_bad_lines, delim_whitespace, low_memory, memory_map, float_precision, storage_options)[0m
[0;32m    608[0m     [0mkwds[0m[1;33m.[0m[0mupdate[0m[1;33m([0m[0mkwds_defaults[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0;32m    609[0m [1;33m[0m[0m
[1;32m--> 610[1;33m     [1;32mreturn[0m [0m_read[0m[1;33m([0m[0mfilepath_or_buffer[0m[1;33m,[0m [0mkwds[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m    611[0m [1;33m[0m[0m
[0;32m    612[0m [1;33m[0m[0m

[1;32m~\Anaconda3\envs\JupyterBook_env\lib\site-packages\pandas\io\parsers.py[0m in [0;36m_read[1;34m(filepath_or_buffer, kwds)[0m
[0;32m    460[0m [1;33m[0m[0m
[0;32m    461[0m     [1;31m# Create the parser.[0m[1;33m[0m[1;33m[0m[1;33m[0m[0m
[1;32m--> 462[1;33m     [0mparser[0m [1;33m=[0m [0mTextFileReader[0m[1;33m([0m[0mfilepath_or_buffer[0m[1;33m,[0m [1;33m**[0m[0mkwds[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m    463[0m [1;33m[0m[0m
[0;32m    464[0m     [1;32mif[0m [0mchunksize[0m [1;32mor[0m [0miterator[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m

[1;32m~\Anaconda3\envs\JupyterBook_env\lib\site-packages\pandas\io\parsers.py[0m in [0;36m__init__[1;34m(self, f, engine, **kwds)[0m
[0;32m    817[0m             [0mself[0m[1;33m.[0m[0moptions[0m[1;33m[[0m[1;34m"has_index_names"[0m[1;33m][0m [1;33m=[0m [0mkwds[0m[1;33m[[0m[1;34m"has_index_names"[0m[1;33m][0m[1;33m[0m[1;33m[0m[0m
[0;32m    818[0m [1;33m[0m[0m
[1;32m--> 819[1;33m         [0mself[0m[1;33m.[0m[0m_engine[0m [1;33m=[0m [0mself[0m[1;33m.[0m[0m_make_engine[0m[1;33m([0m[0mself[0m[1;33m.[0m[0mengine[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m    820[0m [1;33m[0m[0m
[0;32m    821[0m     [1;32mdef[0m [0mclose[0m[1;33m([0m[0mself[0m[1;33m)[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m

[1;32m~\Anaconda3\envs\JupyterBook_env\lib\site-packages\pandas\io\parsers.py[0m in [0;36m_make_engine[1;34m(self, engine)[0m
[0;32m   1048[0m             )
[0;32m   1049[0m         [1;31m# error: Too many arguments for "ParserBase"[0m[1;33m[0m[1;33m[0m[1;33m[0m[0m
[1;32m-> 1050[1;33m         [1;32mreturn[0m [0mmapping[0m[1;33m[[0m[0mengine[0m[1;33m][0m[1;33m([0m[0mself[0m[1;33m.[0m[0mf[0m[1;33m,[0m [1;33m**[0m[0mself[0m[1;33m.[0m[0moptions[0m[1;33m)[0m  [1;31m# type: ignore[call-arg][0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m   1051[0m [1;33m[0m[0m
[0;32m   1052[0m     [1;32mdef[0m [0m_failover_to_python[0m[1;33m([0m[0mself[0m[1;33m)[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m

[1;32m~\Anaconda3\envs\JupyterBook_env\lib\site-packages\pandas\io\parsers.py[0m in [0;36m__init__[1;34m(self, f, **kwds)[0m
[0;32m   2291[0m             [0mself[0m[1;33m.[0m[0mdata[0m [1;33m=[0m [0mcast[0m[1;33m([0m[0mIterator[0m[1;33m[[0m[0mstr[0m[1;33m][0m[1;33m,[0m [0mf[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0;32m   2292[0m         [1;32melse[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[1;32m-> 2293[1;33m             [0mself[0m[1;33m.[0m[0m_open_handles[0m[1;33m([0m[0mf[0m[1;33m,[0m [0mkwds[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m   2294[0m             [1;32massert[0m [0mself[0m[1;33m.[0m[0mhandles[0m [1;32mis[0m [1;32mnot[0m [1;32mNone[0m[1;33m[0m[1;33m[0m[0m
[0;32m   2295[0m             [1;32massert[0m [0mhasattr[0m[1;33m([0m[0mself[0m[1;33m.[0m[0mhandles[0m[1;33m.[0m[0mhandle[0m[1;33m,[0m [1;34m"readline"[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m

[1;32m~\Anaconda3\envs\JupyterBook_env\lib\site-packages\pandas\io\parsers.py[0m in [0;36m_open_handles[1;34m(self, src, kwds)[0m
[0;32m   1360[0m         [0mLet[0m [0mthe[0m [0mreaders[0m [0mopen[0m [0mIOHanldes[0m [0mafter[0m [0mthey[0m [0mare[0m [0mdone[0m [1;32mwith[0m [0mtheir[0m [0mpotential[0m [0mraises[0m[1;33m.[0m[1;33m[0m[1;33m[0m[0m
[0;32m   1361[0m         """
[1;32m-> 1362[1;33m         self.handles = get_handle(
[0m[0;32m   1363[0m             [0msrc[0m[1;33m,[0m[1;33m[0m[1;33m[0m[0m
[0;32m   1364[0m             [1;34m"r"[0m[1;33m,[0m[1;33m[0m[1;33m[0m[0m

[1;32m~\Anaconda3\envs\JupyterBook_env\lib\site-packages\pandas\io\common.py[0m in [0;36mget_handle[1;34m(path_or_buf, mode, encoding, compression, memory_map, is_text, errors, storage_options)[0m
[0;32m    640[0m                 [0merrors[0m [1;33m=[0m [1;34m"replace"[0m[1;33m[0m[1;33m[0m[0m
[0;32m    641[0m             [1;31m# Encoding[0m[1;33m[0m[1;33m[0m[1;33m[0m[0m
[1;32m--> 642[1;33m             handle = open(
[0m[0;32m    643[0m                 [0mhandle[0m[1;33m,[0m[1;33m[0m[1;33m[0m[0m
[0;32m    644[0m                 [0mioargs[0m[1;33m.[0m[0mmode[0m[1;33m,[0m[1;33m[0m[1;33m[0m[0m

[1;31mFileNotFoundError[0m: [Errno 2] No such file or directory: 'E:/UKPDC/JupyterExample/AGAP_BAS_Grav.XYZ'
FileNotFoundError: [Errno 2] No such file or directory: 'E:/UKPDC/JupyterExample/AGAP_BAS_Grav.XYZ'

