Traceback (most recent call last):
  File "C:\Users\almand\Anaconda3\envs\JupyterBook_env\lib\site-packages\jupyter_cache\executors\utils.py", line 51, in single_nb_execution
    executenb(
  File "C:\Users\almand\Anaconda3\envs\JupyterBook_env\lib\site-packages\nbclient\client.py", line 1093, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\almand\Anaconda3\envs\JupyterBook_env\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Users\almand\Anaconda3\envs\JupyterBook_env\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "C:\Users\almand\Anaconda3\envs\JupyterBook_env\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:\Users\almand\Anaconda3\envs\JupyterBook_env\lib\site-packages\nbclient\client.py", line 559, in async_execute
    await self.async_execute_cell(
  File "C:\Users\almand\Anaconda3\envs\JupyterBook_env\lib\site-packages\nbclient\client.py", line 854, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "C:\Users\almand\Anaconda3\envs\JupyterBook_env\lib\site-packages\nbclient\client.py", line 756, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import numpy as np
import gdal
import pandas as pd
import os
import glob
import math
from scipy.stats import iqr
import geopandas as gpd
from pathlib import Path
import warnings

from shapefile_processing.ll2ps_projection import stereosouth_lonlat2xy# for lon/lat to xy projection (see stereosouth_xy2lonlat function)
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mModuleNotFoundError[0m                       Traceback (most recent call last)
[1;32m<ipython-input-2-6955d67b8de5>[0m in [0;36m<module>[1;34m[0m
[0;32m     10[0m [1;32mimport[0m [0mwarnings[0m[1;33m[0m[1;33m[0m[0m
[0;32m     11[0m [1;33m[0m[0m
[1;32m---> 12[1;33m [1;32mfrom[0m [0mshapefile_processing[0m[1;33m.[0m[0mll2ps_projection[0m [1;32mimport[0m [0mstereosouth_lonlat2xy[0m[1;31m# for lon/lat to xy projection (see stereosouth_xy2lonlat function)[0m[1;33m[0m[1;33m[0m[0m
[0m
[1;31mModuleNotFoundError[0m: No module named 'shapefile_processing'
ModuleNotFoundError: No module named 'shapefile_processing'

